# Generated by Django 6.0.3 on 2026-03-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('tf_points_awarded', models.IntegerField(default=0)),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('point_to_unlock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('tf_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField()),
                ('submission_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=255)),
                ('submission_link', models.URLField(blank=True, null=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='submission_files/')),
                ('submission_image', models.ImageField(blank=True, null=True, upload_to='submission_images/')),
                ('comments', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
        ),
    ]
