# Generated by Django 6.0.3 on 2026-03-19 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='submission_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
