# Generated by Django 6.0.3 on 2026-03-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_projectsubmission_id_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='submission_status',
            field=models.CharField(choices=[('not submitted', 'Not Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=255),
        ),
    ]
