# Generated by Django 6.0.3 on 2026-03-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_projectsubmission_submission_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectsubmission',
            unique_together={('user', 'project')},
        ),
    ]
