# Generated by Django 6.0.3 on 2026-03-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_projectsubmission_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='submission_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
